//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Conpass { get; set; }
        public Nullable<long> contactno { get; set; }
        public string Hobby1 { get; set; }
        public string Hobby2 { get; set; }
        public string Hobby3 { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
    }
}
