//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consuming_Data_ASP_DOTNET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int UserId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string hobby1 { get; set; }
        public string hobby2 { get; set; }
        public string city { get; set; }
    }
}
